version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: server
    ports:
      - 8080:80
    links:
      - "db:database"
    restart: always
    volumes:
      - ./server/www:/var/www/html/
  db:
    container_name: db
    image: mariadb:10.4
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./server/db:/var/lib/mysql
